[package]
name = "chat-auth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15.0"
rocket = "0.5.0-rc.1"
diesel = { version = "1.4.4", features = ["postgres", "chrono"] }
